[package]
name = "sx"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
sierra = true
casm = true
casm-add-pythonic-hints = true

[dependencies]
openzeppelin = { git = "https://github.com/ericnordelo/cairo-contracts", branch = "feat/erc20votes-#631" }
starknet = ">=2.2.0"

[scripts]
run-lib = "cairo-run src/lib.cairo"
