[package]
name = "sx"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
casm = true

[dependencies]
starknet = ">=2.1.0-rc1"

[scripts]
run-lib = "cairo-run src/lib.cairo"

# [lib]

