name: Lint
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # run-linters:
  #   name: Run linters
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Check out Git repository
  #       uses: actions/checkout@v2

  #     - name: Set up node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 14

  #     - name: Install dependencies
  #       run: yarn install

  #     - name: Run linters
  #       run: yarn lint:l1

  run-linters-l2:
    name: l2 linting 
    runs-on: ubuntu-latest 

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2   

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Run l2 linters 
        run: yarn lint:l2

  