name: Tests
on:
  push:
    branches:
      - develop
  pull_request:
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Fossil submodule
        run: git submodule update --init --recursive
        
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-
      - name: Install yarn dependencies
        run: yarn install --no-progress --non-interactive

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          sudo apt install -y libgmp3-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Compile Contracts
        run: yarn compile

      - name: Run Cross Chain Tests
        run: yarn test:crosschain:ci
          
      - name: Run L1 tests
        run: yarn test:l1 
        
      - name: Run L2 tests 
        run: yarn test:l2:ci
